global:
  slack_api_url: 'https://hooks.slack.com/services/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'
route:
  receiver: 'slack-notifications'
receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
