services:
  prometheus: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data:/prometheus
    command:
        - "--config.file=/etc/prometheus/prometheus.yml"

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes: 
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"

volumes:
  prometheus_data: {}
  alertmanager_data: {}
