global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: [TARGET_IP:9090]
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
