global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - ${TARGET_IP}:9090
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
